### ISSUE TITLE
N'arrive pas à cliquer sur le masque d'une ligne nouvellement créée

### ISSUE THREAD

**Issue by gabays** [FoNDUE-HTR/Documentation#10]
J'utilise un PC HP de l'uni, et j'utilise comme navigateur Firefox 91.8.0 et quand je crée une ligne, je ne peux pas cliquer sur le masque de cette ligne.
Projet `DigitalJura_prints`, Lot_8, Vue 9. Le lien est le suivant:
https://test2.fondue.unige.ch/document/90/part/3109/edit/
Merci!

**Comment by pkzli** [comment]
Est-ce que c'est en lien avec les problèmes d'affichage discuté dans #14 ? SI oui pourrais tu fermer cette issue ? Merci

**Comment by gabays** [comment]
oui c'est bon
