### ISSUE TITLE
Display problems on eScriptorium

### ISSUE THREAD

**Issue by PaulineJac** [FoNDUE-HTR/Documentation#14]
Hello to the Fondue team!

The Cordel beta testers have encountered problems in the last few weeks when using the eScriptorium platform. 
We are all working on MacBooks with the latest update of Mac Os. 
The following problems have appeared: 
- The transcription part didn't display completely on Safari web browser (Version 15.6.1) and Google Crome (Version 106.0.5249.119). 
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/61355979/199425784-c61ea4b1-69b8-432d-b299-d74f54484f5e.png">

- On Firefox (Version 106.0.3) the lines are displayed partially and staggered, and the masks are entirely missing. 
![SAYNETE COMPLÉT](https://user-images.githubusercontent.com/61355979/199425250-82ffd63f-c9e2-4fd1-b02a-be598b2d3452.png)

On an older version of Firefox (105.0.1) everything works fine. 

Thanks for your help. 
Have a nice day, 
Pauline

**Comment by pkzli** [comment]
Hi, I get the same problem, it seems that @gabays as well and that the problem exist on the Paris instance too (on which I have no access). I'll try to investigate but it's probably a bug that will need an update of escriptorium once fixed.

**Comment by PaulineJac** [comment]
Understood. 
Thank you for the very quick response 😄.

**Comment by pkzli** [comment]
Ok I'll update our instance at some point, maybe it'll fix the bug at the same time

**Comment by PaulineJac** [comment]
> 

Hello, I have just done some tests and the problems are still there.

**Comment by pkzli** [comment]
Yes I'm using escriptorium currently for a project and I agree those bugs are quite annoying. Unfortunately while I have lot of other tasks it's difficult to plan some time to do the update. I hope I will be able to do it before the end of the year. I propose that we let this issue open and I'll notify you once the update is done.
