### ISSUE TITLE
Job started 5 days ago without progress

### ISSUE THREAD

**Issue by PaulineJac** [FoNDUE-HTR/Documentation#9]
Hello, 
I have started a model's re-training on Fondue and it has not shown any progress for more than a week. Do you have any idea what is causing this? 
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/61355979/149509144-395c882a-e1ba-42d4-8ca3-423291ae9122.png">

**Comment by pkzli** [comment]
Bonjour, désolé pour la réponse (très) tardive, avez vous remarqué ce genre de phénomène à nouveau ?

**Comment by gabays** [comment]
Pas de nouvelle. je ferme, on rouvrira si ça recommence.

**Comment by PaulineJac** [comment]
Bonjour, 

Je viens de refaire un essai et ce problème ne semble plus d'actualité. Merci pour tout.
Belle journée, 
Pauline
